apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pipeline-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-pipeline-demo
  template:
    metadata:
      labels:
        app: jenkins-pipeline-demo
    spec:
      containers:
        - name: jenkins-pipeline-demo
          image: sangnt8386/flask-app-pipeline:1.0.0-36
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
