apiVersion: v1
kind: Service
metadata:
  name: jenkins-pipeline-demo-service
  labels:
    app: jenkins-pipeline-demo 
spec:
  selector:
    app: jenkins-pipeline-demo

  ports:
    - port: 80
      targetPort: 5000

  type: LoadBalancer
